url: https://easyscience.software
title: Making scientific data analysis and modelling easy
description: >-
  A Python/QML framework for data analysis being developed to speed-up the time
  from data collection to publication.
